json.staffing_level_number @staffing_level[:staffing_level_number]
json.staffing_level_name @staffing_level[:staffing_level_name]
json.staffing_level_percentage @staffing_level[:staffing_level_percentage]